"""
Copyright 2017 Ryan Wick (rrwick@gmail.com)
https://github.com/rrwick/Porechop

This module contains the class and sequences for known adapters used in Oxford Nanopore library
preparation kits.

This file is part of Porechop. Porechop is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by the Free Software Foundation,
either version 3 of the License, or (at your option) any later version. Porechop is distributed in
the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
details. You should have received a copy of the GNU General Public License along with Porechop. If
not, see <http://www.gnu.org/licenses/>.
"""


class Adapter(object):

	def __init__(self, name, start_sequence=None, end_sequence=None, both_ends_sequence=None):
		self.name = name
		self.start_sequence = start_sequence if start_sequence else []
		self.end_sequence = end_sequence if end_sequence else []
		if both_ends_sequence:
			self.start_sequence = both_ends_sequence
			self.end_sequence = both_ends_sequence
		self.best_start_score, self.best_end_score = 0.0, 0.0
		self.sum_start_scores, self.sum_end_scores = 0.0, 0.0

	def best_start_or_end_score(self):
		return max(self.best_start_score, self.best_end_score)

	def is_barcode(self):
		return self.name.startswith('Barcode ')

	def barcode_direction(self):
		if '_rev' in self.start_sequence[0]:
			return 'reverse'
		else:
			return 'forward'

	def get_barcode_name(self):
		"""
		Gets the barcode name for the output files. We want a concise name, so it looks at all
		options and chooses the shortest.
		"""
		possible_names = [self.name]
		if self.start_sequence:
			possible_names.append(self.start_sequence[0])
		if self.end_sequence:
			possible_names.append(self.end_sequence[0])
		barcode_name = sorted(possible_names, key=lambda x: len(x))[0]
		return barcode_name.replace(' ', '_')


# INSTRUCTIONS FOR ADDING CUSTOM ADAPTERS
# ---------------------------------------
# If you need Porechop to remove adapters that aren't included, you can add your own my modifying
# the ADAPTERS list below.
#
# Here is the format for a normal adapter:
#	 Adapter('Adapter_set_name',
#		 start_sequence=('Start_adapter_name', 'AAAACCCCGGGGTTTTAAAACCCCGGGGTTTT'),
#		 end_sequence=('End_adapter_name', 'AACCGGTTAACCGGTTAACCGGTTAACCGGTT'))
#
# You can exclude start_sequence and end_sequence as appropriate.
#
# If you have custom Barcodes, make sure that the adapter set name starts with 'Barcode '. Also,
# remove the existing barcode sequences from this file to avoid conflicts:
#	 Adapter('Barcode 1',
#		 start_sequence=('Barcode_1_start', 'AAAAAAAACCCCCCCCGGGGGGGGTTTTTTTT'),
#		 end_sequence=('Barcode_1_end', 'AAAAAAAACCCCCCCCGGGGGGGGTTTTTTTT')),
#	 Adapter('Barcode 2',
#		 start_sequence=('Barcode_2_start', 'TTTTTTTTGGGGGGGGCCCCCCCCAAAAAAAA'),
#		 end_sequence=('Barcode_2_end', 'TTTTTTTTGGGGGGGGCCCCCCCCAAAAAAAA'))


# ADAPTERS = [
# 	# TAKARA Template-switching oligo (TSO).
# 	Adapter('TAKARA TSO (1)',
# 		start_sequence=('TSO1', 'ACTCTTTCCCTACACGACGCTCTTCCGATCTATTGCGCAATG'),
#         end_sequence=('TSO1_end', 'CATTGCGCAATAGATCGGAAGAGCGTCGTGTAGGGAAAGAGT')),
# 	Adapter('TAKARA TSO (2)',
# 		start_sequence=('TSO2', 'CATTGCGCAATAGATCGGAAGAGCGTCGTGTAGGGAAAGAGT'),
#         end_sequence=('TSO2_end', 'ACTCTTTCCCTACACGACGCTCTTCCGATCTATTGCGCAATG'))
# ]

ADAPTERS = [
	# Tiwts dual indexes, in both orientations.
	Adapter('Barcode 1 (forward)',
		start_sequence=('A01_i5_F', 'CCAATATTCG'),
		end_sequence=('A01_i7_F', 'TATCTTCAGC')),
	Adapter('Barcode 1 (reverse)',
		start_sequence=('A01_i7_R', 'GCTGAAGATA'),
		end_sequence=('A01_i5_R', 'CGAATATTGG')),
	Adapter('Barcode 2 (forward)',
		start_sequence=('B01_i5_F', 'CGCAGACAAC'),
		end_sequence=('B01_i7_F', 'TGCACGGATA')),
	Adapter('Barcode 2 (reverse)',
		start_sequence=('B01_i7_R', 'TATCCGTGCA'),
		end_sequence=('B01_i5_R', 'GTTGTCTGCG')),
	Adapter('Barcode 3 (forward)',
		start_sequence=('C01_i5_F', 'TCGGAGCAGA'),
		end_sequence=('C01_i7_F', 'GGTTGATAGA')),
	Adapter('Barcode 3 (reverse)',
		start_sequence=('C01_i7_R', 'TCTATCAACC'),
		end_sequence=('C01_i5_R', 'TCTGCTCCGA')),
	Adapter('Barcode 4 (forward)',
		start_sequence=('D01_i5_F', 'GAGTCCGTAG'),
		end_sequence=('D01_i7_F', 'ACTCCTGCCT')),
	Adapter('Barcode 4 (reverse)',
		start_sequence=('D01_i7_R', 'AGGCAGGAGT'),
		end_sequence=('D01_i5_R', 'CTACGGACTC')),
	Adapter('Barcode 5 (forward)',
		start_sequence=('E01_i5_F', 'ATGTTCACGT'),
		end_sequence=('E01_i7_F', 'CCGATAGTCG')),
	Adapter('Barcode 5 (reverse)',
		start_sequence=('E01_i7_R', 'CGACTATCGG'),
		end_sequence=('E01_i5_R', 'ACGTGAACAT')),
	Adapter('Barcode 6 (forward)',
		start_sequence=('F01_i5_F', 'TTCGATGGTT'),
		end_sequence=('F01_i7_F', 'CAAGATCGAA')),
	Adapter('Barcode 6 (reverse)',
		start_sequence=('F01_i7_R', 'TTCGATCTTG'),
		end_sequence=('F01_i5_R', 'AACCATCGAA')),
	Adapter('Barcode 7 (forward)',
		start_sequence=('G01_i5_F', 'TATCCGTGCA'),
		end_sequence=('G01_i7_F', 'AGGCTCCTTC')),
	Adapter('Barcode 7 (reverse)',
		start_sequence=('G01_i7_R', 'GAAGGAGCCT'),
		end_sequence=('G01_i5_R', 'TGCACGGATA')),
	Adapter('Barcode 8 (forward)',
		start_sequence=('H01_i5_F', 'AAGCGCAGAG'),
		end_sequence=('H01_i7_F', 'ATACGGATAG')),
	Adapter('Barcode 8 (reverse)',
		start_sequence=('H01_i7_R', 'CTATCCGTAT'),
		end_sequence=('H01_i5_R', 'CTCTGCGCTT')),
	Adapter('Barcode 9 (forward)',
		start_sequence=('A02_i5_F', 'CCGACTTAGT'),
		end_sequence=('A02_i7_F', 'AATAGCCTCA')),
	Adapter('Barcode 9 (reverse)',
		start_sequence=('A02_i7_R', 'TGAGGCTATT'),
		end_sequence=('A02_i5_R', 'ACTAAGTCGG')),
	Adapter('Barcode 10 (forward)',
		start_sequence=('B02_i5_F', 'TTCTGCATCG'),
		end_sequence=('B02_i7_F', 'CTGCAATCGG')),
	Adapter('Barcode 10 (reverse)',
		start_sequence=('B02_i7_R', 'CCGATTGCAG'),
		end_sequence=('B02_i5_R', 'CGATGCAGAA')),
	Adapter('Barcode 11 (forward)',
		start_sequence=('C02_i5_F', 'GGAAGTGCCA'),
		end_sequence=('C02_i7_F', 'CCTGAGTTAT')),
	Adapter('Barcode 11 (reverse)',
		start_sequence=('C02_i7_R', 'ATAACTCAGG'),
		end_sequence=('C02_i5_R', 'TGGCACTTCC')),
	Adapter('Barcode 12 (forward)',
		start_sequence=('D02_i5_F', 'AGATTCAACC'),
		end_sequence=('D02_i7_F', 'GACGTCCAGA')),
	Adapter('Barcode 12 (reverse)',
		start_sequence=('D02_i7_R', 'TCTGGACGTC'),
		end_sequence=('D02_i5_R', 'GGTTGAATCT')),
	Adapter('Barcode 13 (forward)',
		start_sequence=('E02_i5_F', 'TTCAGGAGAT'),
		end_sequence=('E02_i7_F', 'GAATAATCGG')),
	Adapter('Barcode 13 (reverse)',
		start_sequence=('E02_i7_R', 'CCGATTATTC'),
		end_sequence=('E02_i5_R', 'ATCTCCTGAA')),
	Adapter('Barcode 14 (forward)',
		start_sequence=('F02_i5_F', 'AAGGCGTCTG'),
		end_sequence=('F02_i7_F', 'CGGAGTGTGT')),
	Adapter('Barcode 14 (reverse)',
		start_sequence=('F02_i7_R', 'ACACACTCCG'),
		end_sequence=('F02_i5_R', 'CAGACGCCTT')),
	Adapter('Barcode 15 (forward)',
		start_sequence=('G02_i5_F', 'ACGCTTGACA'),
		end_sequence=('G02_i7_F', 'TTACCGACCG')),
	Adapter('Barcode 15 (reverse)',
		start_sequence=('G02_i7_R', 'CGGTCGGTAA'),
		end_sequence=('G02_i5_R', 'TGTCAAGCGT')),
	Adapter('Barcode 16 (forward)',
		start_sequence=('H02_i5_F', 'CATGAAGTGA'),
		end_sequence=('H02_i7_F', 'AGTGTTCGCC')),
	Adapter('Barcode 16 (reverse)',
		start_sequence=('H02_i7_R', 'GGCGAACACT'),
		end_sequence=('H02_i5_R', 'TCACTTCATG')),
	Adapter('Barcode 17 (forward)',
		start_sequence=('A03_i5_F', 'TTACGACCTG'),
		end_sequence=('A03_i7_F', 'CTACGTTCTT')),
	Adapter('Barcode 17 (reverse)',
		start_sequence=('A03_i7_R', 'AAGAACGTAG'),
		end_sequence=('A03_i5_R', 'CAGGTCGTAA')),
	Adapter('Barcode 18 (forward)',
		start_sequence=('B03_i5_F', 'ATGCAAGCCG'),
		end_sequence=('B03_i7_F', 'TCGACACGAA')),
	Adapter('Barcode 18 (reverse)',
		start_sequence=('B03_i7_R', 'TTCGTGTCGA'),
		end_sequence=('B03_i5_R', 'CGGCTTGCAT')),
	Adapter('Barcode 19 (forward)',
		start_sequence=('C03_i5_F', 'CTCCGTATAC'),
		end_sequence=('C03_i7_F', 'CCGATAACTT')),
	Adapter('Barcode 19 (reverse)',
		start_sequence=('C03_i7_R', 'AAGTTATCGG'),
		end_sequence=('C03_i5_R', 'GTATACGGAG')),
	Adapter('Barcode 20 (forward)',
		start_sequence=('D03_i5_F', 'GAATCTGGTC'),
		end_sequence=('D03_i7_F', 'TTGGACATCG')),
	Adapter('Barcode 20 (reverse)',
		start_sequence=('D03_i7_R', 'CGATGTCCAA'),
		end_sequence=('D03_i5_R', 'GACCAGATTC')),
	Adapter('Barcode 21 (forward)',
		start_sequence=('E03_i5_F', 'CGGTCGGTAA'),
		end_sequence=('E03_i7_F', 'AACGTTGAGA')),
	Adapter('Barcode 21 (reverse)',
		start_sequence=('E03_i7_R', 'TCTCAACGTT'),
		end_sequence=('E03_i5_R', 'TTACCGACCG')),
	Adapter('Barcode 22 (forward)',
		start_sequence=('F03_i5_F', 'TCTGCTAATG'),
		end_sequence=('F03_i7_F', 'GGCCAGTGAA')),
	Adapter('Barcode 22 (reverse)',
		start_sequence=('F03_i7_R', 'TTCACTGGCC'),
		end_sequence=('F03_i5_R', 'CATTAGCAGA')),
	Adapter('Barcode 23 (forward)',
		start_sequence=('G03_i5_F', 'CTCTTATTCG'),
		end_sequence=('G03_i7_F', 'ATGTCTCCGG')),
	Adapter('Barcode 23 (reverse)',
		start_sequence=('G03_i7_R', 'CCGGAGACAT'),
		end_sequence=('G03_i5_R', 'CGAATAAGAG')),
	Adapter('Barcode 24 (forward)',
		start_sequence=('H03_i5_F', 'CACCTCTAGC'),
		end_sequence=('H03_i7_F', 'GAAGGCGTTC')),
	Adapter('Barcode 24 (reverse)',
		start_sequence=('H03_i7_R', 'GAACGCCTTC'),
		end_sequence=('H03_i5_R', 'GCTAGAGGTG')),
	Adapter('Barcode 25 (forward)',
		start_sequence=('A04_i5_F', 'TTACTTACCG'),
		end_sequence=('A04_i7_F', 'TGTTCCTAGA')),
	Adapter('Barcode 25 (reverse)',
		start_sequence=('A04_i7_R', 'TCTAGGAACA'),
		end_sequence=('A04_i5_R', 'CGGTAAGTAA')),
	Adapter('Barcode 26 (forward)',
		start_sequence=('B04_i5_F', 'CTATGCCTTA'),
		end_sequence=('B04_i7_F', 'CTCTCGAGGT')),
	Adapter('Barcode 26 (reverse)',
		start_sequence=('B04_i7_R', 'ACCTCGAGAG'),
		end_sequence=('B04_i5_R', 'TAAGGCATAG')),
	Adapter('Barcode 27 (forward)',
		start_sequence=('C04_i5_F', 'GGAAGGTACG'),
		end_sequence=('C04_i7_F', 'CTGTACGGTA')),
	Adapter('Barcode 27 (reverse)',
		start_sequence=('C04_i7_R', 'TACCGTACAG'),
		end_sequence=('C04_i5_R', 'CGTACCTTCC')),
	Adapter('Barcode 28 (forward)',
		start_sequence=('D04_i5_F', 'GAGGAGACGT'),
		end_sequence=('D04_i7_F', 'CTTATGGCAA')),
	Adapter('Barcode 28 (reverse)',
		start_sequence=('D04_i7_R', 'TTGCCATAAG'),
		end_sequence=('D04_i5_R', 'ACGTCTCCTC')),
	Adapter('Barcode 29 (forward)',
		start_sequence=('E04_i5_F', 'ACGCAAGGCA'),
		end_sequence=('E04_i7_F', 'TCCGCATAGC')),
	Adapter('Barcode 29 (reverse)',
		start_sequence=('E04_i7_R', 'GCTATGCGGA'),
		end_sequence=('E04_i5_R', 'TGCCTTGCGT')),
	Adapter('Barcode 30 (forward)',
		start_sequence=('F04_i5_F', 'TATCCTGACG'),
		end_sequence=('F04_i7_F', 'GCAAGCACCT')),
	Adapter('Barcode 30 (reverse)',
		start_sequence=('F04_i7_R', 'AGGTGCTTGC'),
		end_sequence=('F04_i5_R', 'CGTCAGGATA')),
	Adapter('Barcode 31 (forward)',
		start_sequence=('G04_i5_F', 'GAAGACCGCT'),
		end_sequence=('G04_i7_F', 'GCCTGTCCTA')),
	Adapter('Barcode 31 (reverse)',
		start_sequence=('G04_i7_R', 'TAGGACAGGC'),
		end_sequence=('G04_i5_R', 'AGCGGTCTTC')),
	Adapter('Barcode 32 (forward)',
		start_sequence=('H04_i5_F', 'CAACGTGGAC'),
		end_sequence=('H04_i7_F', 'ACTGTCTATC')),
	Adapter('Barcode 32 (reverse)',
		start_sequence=('H04_i7_R', 'GATAGACAGT'),
		end_sequence=('H04_i5_R', 'GTCCACGTTG')),
	Adapter('Barcode 33 (forward)',
		start_sequence=('A05_i5_F', 'TAAGTGCTCG'),
		end_sequence=('A05_i7_F', 'CGTCCATGTA')),
	Adapter('Barcode 33 (reverse)',
		start_sequence=('A05_i7_R', 'TACATGGACG'),
		end_sequence=('A05_i5_R', 'CGAGCACTTA')),
	Adapter('Barcode 34 (forward)',
		start_sequence=('B05_i5_F', 'CACATCGTAG'),
		end_sequence=('B05_i7_F', 'CTAACTGCAA')),
	Adapter('Barcode 34 (reverse)',
		start_sequence=('B05_i7_R', 'TTGCAGTTAG'),
		end_sequence=('B05_i5_R', 'CTACGATGTG')),
	Adapter('Barcode 35 (forward)',
		start_sequence=('C05_i5_F', 'ACTACCGAGG'),
		end_sequence=('C05_i7_F', 'TGCTTGTGGT')),
	Adapter('Barcode 35 (reverse)',
		start_sequence=('C05_i7_R', 'ACCACAAGCA'),
		end_sequence=('C05_i5_R', 'CCTCGGTAGT')),
	Adapter('Barcode 36 (forward)',
		start_sequence=('D05_i5_F', 'GATGTGTTCT'),
		end_sequence=('D05_i7_F', 'TGTAAGCACA')),
	Adapter('Barcode 36 (reverse)',
		start_sequence=('D05_i7_R', 'TGTGCTTACA'),
		end_sequence=('D05_i5_R', 'AGAACACATC')),
	Adapter('Barcode 37 (forward)',
		start_sequence=('E05_i5_F', 'AAGTGTCGTA'),
		end_sequence=('E05_i7_F', 'CTCGTTGCGT')),
	Adapter('Barcode 37 (reverse)',
		start_sequence=('E05_i7_R', 'ACGCAACGAG'),
		end_sequence=('E05_i5_R', 'TACGACACTT')),
	Adapter('Barcode 38 (forward)',
		start_sequence=('F05_i5_F', 'GGAGAACCAC'),
		end_sequence=('F05_i7_F', 'GCTAGAGGTG')),
	Adapter('Barcode 38 (reverse)',
		start_sequence=('F05_i7_R', 'CACCTCTAGC'),
		end_sequence=('F05_i5_R', 'GTGGTTCTCC')),
	Adapter('Barcode 39 (forward)',
		start_sequence=('G05_i5_F', 'TGTACGAACT'),
		end_sequence=('G05_i7_F', 'AAGCGGAGAA')),
	Adapter('Barcode 39 (reverse)',
		start_sequence=('G05_i7_R', 'TTCTCCGCTT'),
		end_sequence=('G05_i5_R', 'AGTTCGTACA')),
	Adapter('Barcode 40 (forward)',
		start_sequence=('H05_i5_F', 'GGATGAGTGC'),
		end_sequence=('H05_i7_F', 'AATGACGCTG')),
	Adapter('Barcode 40 (reverse)',
		start_sequence=('H05_i7_R', 'CAGCGTCATT'),
		end_sequence=('H05_i5_R', 'GCACTCATCC')),
	Adapter('Barcode 41 (forward)',
		start_sequence=('A06_i5_F', 'TAGTAGGACA'),
		end_sequence=('A06_i7_F', 'TTGGTACGCG')),
	Adapter('Barcode 41 (reverse)',
		start_sequence=('A06_i7_R', 'CGCGTACCAA'),
		end_sequence=('A06_i5_R', 'TGTCCTACTA')),
	Adapter('Barcode 42 (forward)',
		start_sequence=('B06_i5_F', 'ACGCCTCGTT'),
		end_sequence=('B06_i7_F', 'TGAAGGTGAA')),
	Adapter('Barcode 42 (reverse)',
		start_sequence=('B06_i7_R', 'TTCACCTTCA'),
		end_sequence=('B06_i5_R', 'AACGAGGCGT')),
	Adapter('Barcode 43 (forward)',
		start_sequence=('C06_i5_F', 'CACCGCTGTT'),
		end_sequence=('C06_i7_F', 'GTAGTGGCTT')),
	Adapter('Barcode 43 (reverse)',
		start_sequence=('C06_i7_R', 'AAGCCACTAC'),
		end_sequence=('C06_i5_R', 'AACAGCGGTG')),
	Adapter('Barcode 44 (forward)',
		start_sequence=('D06_i5_F', 'TCTATAGCGG'),
		end_sequence=('D06_i7_F', 'CGTAACAGAA')),
	Adapter('Barcode 44 (reverse)',
		start_sequence=('D06_i7_R', 'TTCTGTTACG'),
		end_sequence=('D06_i5_R', 'CCGCTATAGA')),
	Adapter('Barcode 45 (forward)',
		start_sequence=('E06_i5_F', 'CCGATGGACA'),
		end_sequence=('E06_i7_F', 'AAGGCCATAA')),
	Adapter('Barcode 45 (reverse)',
		start_sequence=('E06_i7_R', 'TTATGGCCTT'),
		end_sequence=('E06_i5_R', 'TGTCCATCGG')),
	Adapter('Barcode 46 (forward)',
		start_sequence=('F06_i5_F', 'TTCAACATGC'),
		end_sequence=('F06_i7_F', 'TTCATAGACC')),
	Adapter('Barcode 46 (reverse)',
		start_sequence=('F06_i7_R', 'GGTCTATGAA'),
		end_sequence=('F06_i5_R', 'GCATGTTGAA')),
	Adapter('Barcode 47 (forward)',
		start_sequence=('G06_i5_F', 'GGAGTAACGC'),
		end_sequence=('G06_i7_F', 'CCAACTCCGA')),
	Adapter('Barcode 47 (reverse)',
		start_sequence=('G06_i7_R', 'TCGGAGTTGG'),
		end_sequence=('G06_i5_R', 'GCGTTACTCC')),
	Adapter('Barcode 48 (forward)',
		start_sequence=('H06_i5_F', 'AGCCTTAGCG'),
		end_sequence=('H06_i7_F', 'CACGAGTATG')),
	Adapter('Barcode 48 (reverse)',
		start_sequence=('H06_i7_R', 'CATACTCGTG'),
		end_sequence=('H06_i5_R', 'CGCTAAGGCT')),
	Adapter('Barcode 49 (forward)',
		start_sequence=('A07_i5_F', 'TTACCTCAGT'),
		end_sequence=('A07_i7_F', 'CCGCTACCAA')),
	Adapter('Barcode 49 (reverse)',
		start_sequence=('A07_i7_R', 'TTGGTAGCGG'),
		end_sequence=('A07_i5_R', 'ACTGAGGTAA')),
	Adapter('Barcode 50 (forward)',
		start_sequence=('B07_i5_F', 'CAGGCATTGT'),
		end_sequence=('B07_i7_F', 'CTGAACCTCC')),
	Adapter('Barcode 50 (reverse)',
		start_sequence=('B07_i7_R', 'GGAGGTTCAG'),
		end_sequence=('B07_i5_R', 'ACAATGCCTG')),
	Adapter('Barcode 51 (forward)',
		start_sequence=('C07_i5_F', 'GTGTTCCACG'),
		end_sequence=('C07_i7_F', 'GGCCTTGTTA')),
	Adapter('Barcode 51 (reverse)',
		start_sequence=('C07_i7_R', 'TAACAAGGCC'),
		end_sequence=('C07_i5_R', 'CGTGGAACAC')),
	Adapter('Barcode 52 (forward)',
		start_sequence=('D07_i5_F', 'TTGATCCGCC'),
		end_sequence=('D07_i7_F', 'TTAACGCAGA')),
	Adapter('Barcode 52 (reverse)',
		start_sequence=('D07_i7_R', 'TCTGCGTTAA'),
		end_sequence=('D07_i5_R', 'GGCGGATCAA')),
	Adapter('Barcode 53 (forward)',
		start_sequence=('E07_i5_F', 'GGAGGCTGAT'),
		end_sequence=('E07_i7_F', 'AGGTAGTGCG')),
	Adapter('Barcode 53 (reverse)',
		start_sequence=('E07_i7_R', 'CGCACTACCT'),
		end_sequence=('E07_i5_R', 'ATCAGCCTCC')),
	Adapter('Barcode 54 (forward)',
		start_sequence=('F07_i5_F', 'AACGTGACAA'),
		end_sequence=('F07_i7_F', 'CGTGTAACTT')),
	Adapter('Barcode 54 (reverse)',
		start_sequence=('F07_i7_R', 'AAGTTACACG'),
		end_sequence=('F07_i5_R', 'TTGTCACGTT')),
	Adapter('Barcode 55 (forward)',
		start_sequence=('G07_i5_F', 'CACAAGCTCC'),
		end_sequence=('G07_i7_F', 'ACTTGTGACG')),
	Adapter('Barcode 55 (reverse)',
		start_sequence=('G07_i7_R', 'CGTCACAAGT'),
		end_sequence=('G07_i5_R', 'GGAGCTTGTG')),
	Adapter('Barcode 56 (forward)',
		start_sequence=('H07_i5_F', 'CCGTGTTGTC'),
		end_sequence=('H07_i7_F', 'CCATGCGTTG')),
	Adapter('Barcode 56 (reverse)',
		start_sequence=('H07_i7_R', 'CAACGCATGG'),
		end_sequence=('H07_i5_R', 'GACAACACGG')),
	Adapter('Barcode 57 (forward)',
		start_sequence=('A08_i5_F', 'TTGAGCCAGC'),
		end_sequence=('A08_i7_F', 'CCTTGTAGCG')),
	Adapter('Barcode 57 (reverse)',
		start_sequence=('A08_i7_R', 'CGCTACAAGG'),
		end_sequence=('A08_i5_R', 'GCTGGCTCAA')),
	Adapter('Barcode 58 (forward)',
		start_sequence=('B08_i5_F', 'GCGTTACAGA'),
		end_sequence=('B08_i7_F', 'ACATACGTGA')),
	Adapter('Barcode 58 (reverse)',
		start_sequence=('B08_i7_R', 'TCACGTATGT'),
		end_sequence=('B08_i5_R', 'TCTGTAACGC')),
	Adapter('Barcode 59 (forward)',
		start_sequence=('C08_i5_F', 'TCCAGACATT'),
		end_sequence=('C08_i7_F', 'CTTGATATCC')),
	Adapter('Barcode 59 (reverse)',
		start_sequence=('C08_i7_R', 'GGATATCAAG'),
		end_sequence=('C08_i5_R', 'AATGTCTGGA')),
	Adapter('Barcode 60 (forward)',
		start_sequence=('D08_i5_F', 'TCGAACTCTT'),
		end_sequence=('D08_i7_F', 'CAGCCGATGT')),
	Adapter('Barcode 60 (reverse)',
		start_sequence=('D08_i7_R', 'ACATCGGCTG'),
		end_sequence=('D08_i5_R', 'AAGAGTTCGA')),
	Adapter('Barcode 61 (forward)',
		start_sequence=('E08_i5_F', 'ACCTTCTCGG'),
		end_sequence=('E08_i7_F', 'TCATGCGCTA')),
	Adapter('Barcode 61 (reverse)',
		start_sequence=('E08_i7_R', 'TAGCGCATGA'),
		end_sequence=('E08_i5_R', 'CCGAGAAGGT')),
	Adapter('Barcode 62 (forward)',
		start_sequence=('F08_i5_F', 'AGACGCCAAC'),
		end_sequence=('F08_i7_F', 'ACTCCGTCCA')),
	Adapter('Barcode 62 (reverse)',
		start_sequence=('F08_i7_R', 'TGGACGGAGT'),
		end_sequence=('F08_i5_R', 'GTTGGCGTCT')),
	Adapter('Barcode 63 (forward)',
		start_sequence=('G08_i5_F', 'CAACCGTAAT'),
		end_sequence=('G08_i7_F', 'GACAGCCTTG')),
	Adapter('Barcode 63 (reverse)',
		start_sequence=('G08_i7_R', 'CAAGGCTGTC'),
		end_sequence=('G08_i5_R', 'ATTACGGTTG')),
	Adapter('Barcode 64 (forward)',
		start_sequence=('H08_i5_F', 'TTATGCGTTG'),
		end_sequence=('H08_i7_F', 'CGGTTATCTG')),
	Adapter('Barcode 64 (reverse)',
		start_sequence=('H08_i7_R', 'CAGATAACCG'),
		end_sequence=('H08_i5_R', 'CAACGCATAA')),
	Adapter('Barcode 65 (forward)',
		start_sequence=('A09_i5_F', 'CTATGAGAAC'),
		end_sequence=('A09_i7_F', 'TACTCCACGG')),
	Adapter('Barcode 65 (reverse)',
		start_sequence=('A09_i7_R', 'CCGTGGAGTA'),
		end_sequence=('A09_i5_R', 'GTTCTCATAG')),
	Adapter('Barcode 66 (forward)',
		start_sequence=('B09_i5_F', 'AAGTTACACG'),
		end_sequence=('B09_i7_F', 'ACTTCCGGCA')),
	Adapter('Barcode 66 (reverse)',
		start_sequence=('B09_i7_R', 'TGCCGGAAGT'),
		end_sequence=('B09_i5_R', 'CGTGTAACTT')),
	Adapter('Barcode 67 (forward)',
		start_sequence=('C09_i5_F', 'GCAATGTGAG'),
		end_sequence=('C09_i7_F', 'GTGAAGCTGC')),
	Adapter('Barcode 67 (reverse)',
		start_sequence=('C09_i7_R', 'GCAGCTTCAC'),
		end_sequence=('C09_i5_R', 'CTCACATTGC')),
	Adapter('Barcode 68 (forward)',
		start_sequence=('D09_i5_F', 'CGAAGTCGCA'),
		end_sequence=('D09_i7_F', 'TTGCTCTTCT')),
	Adapter('Barcode 68 (reverse)',
		start_sequence=('D09_i7_R', 'AGAAGAGCAA'),
		end_sequence=('D09_i5_R', 'TGCGACTTCG')),
	Adapter('Barcode 69 (forward)',
		start_sequence=('E09_i5_F', 'CCTGATTCAA'),
		end_sequence=('E09_i7_F', 'AACGCACGTA')),
	Adapter('Barcode 69 (reverse)',
		start_sequence=('E09_i7_R', 'TACGTGCGTT'),
		end_sequence=('E09_i5_R', 'TTGAATCAGG')),
	Adapter('Barcode 70 (forward)',
		start_sequence=('F09_i5_F', 'TAGAACGTGC'),
		end_sequence=('F09_i7_F', 'TTACTGCAGG')),
	Adapter('Barcode 70 (reverse)',
		start_sequence=('F09_i7_R', 'CCTGCAGTAA'),
		end_sequence=('F09_i5_R', 'GCACGTTCTA')),
	Adapter('Barcode 71 (forward)',
		start_sequence=('G09_i5_F', 'TTCGCAAGGT'),
		end_sequence=('G09_i7_F', 'CCAGTTGAGG')),
	Adapter('Barcode 71 (reverse)',
		start_sequence=('G09_i7_R', 'CCTCAACTGG'),
		end_sequence=('G09_i5_R', 'ACCTTGCGAA')),
	Adapter('Barcode 72 (forward)',
		start_sequence=('H09_i5_F', 'TTAATGCCGA'),
		end_sequence=('H09_i7_F', 'TGTGCGTTAA')),
	Adapter('Barcode 72 (reverse)',
		start_sequence=('H09_i7_R', 'TTAACGCACA'),
		end_sequence=('H09_i5_R', 'TCGGCATTAA')),
	Adapter('Barcode 73 (forward)',
		start_sequence=('A10_i5_F', 'AGAACAGAGT'),
		end_sequence=('A10_i7_F', 'ACTAGTGCTT')),
	Adapter('Barcode 73 (reverse)',
		start_sequence=('A10_i7_R', 'AAGCACTAGT'),
		end_sequence=('A10_i5_R', 'ACTCTGTTCT')),
	Adapter('Barcode 74 (forward)',
		start_sequence=('B10_i5_F', 'CCATCTGTTC'),
		end_sequence=('B10_i7_F', 'CGTGGAACAC')),
	Adapter('Barcode 74 (reverse)',
		start_sequence=('B10_i7_R', 'GTGTTCCACG'),
		end_sequence=('B10_i5_R', 'GAACAGATGG')),
	Adapter('Barcode 75 (forward)',
		start_sequence=('C10_i5_F', 'TTCGTAGGTG'),
		end_sequence=('C10_i7_F', 'ATGGAAGTGG')),
	Adapter('Barcode 75 (reverse)',
		start_sequence=('C10_i7_R', 'CCACTTCCAT'),
		end_sequence=('C10_i5_R', 'CACCTACGAA')),
	Adapter('Barcode 76 (forward)',
		start_sequence=('D10_i5_F', 'GCACGGTACA'),
		end_sequence=('D10_i7_F', 'TGAGATCACA')),
	Adapter('Barcode 76 (reverse)',
		start_sequence=('D10_i7_R', 'TGTGATCTCA'),
		end_sequence=('D10_i5_R', 'TGTACCGTGC')),
	Adapter('Barcode 77 (forward)',
		start_sequence=('E10_i5_F', 'TGTCAAGAGG'),
		end_sequence=('E10_i7_F', 'GTCCTTGGTG')),
	Adapter('Barcode 77 (reverse)',
		start_sequence=('E10_i7_R', 'CACCAAGGAC'),
		end_sequence=('E10_i5_R', 'CCTCTTGACA')),
	Adapter('Barcode 78 (forward)',
		start_sequence=('F10_i5_F', 'TCTAAGGTAC'),
		end_sequence=('F10_i7_F', 'GAGCGTGGAA')),
	Adapter('Barcode 78 (reverse)',
		start_sequence=('F10_i7_R', 'TTCCACGCTC'),
		end_sequence=('F10_i5_R', 'GTACCTTAGA')),
	Adapter('Barcode 79 (forward)',
		start_sequence=('G10_i5_F', 'GAACGGAGAC'),
		end_sequence=('G10_i7_F', 'CACACGCTGT')),
	Adapter('Barcode 79 (reverse)',
		start_sequence=('G10_i7_R', 'ACAGCGTGTG'),
		end_sequence=('G10_i5_R', 'GTCTCCGTTC')),
	Adapter('Barcode 80 (forward)',
		start_sequence=('H10_i5_F', 'CGCTACCATC'),
		end_sequence=('H10_i7_F', 'TGGTTGTACA')),
	Adapter('Barcode 80 (reverse)',
		start_sequence=('H10_i7_R', 'TGTACAACCA'),
		end_sequence=('H10_i5_R', 'GATGGTAGCG')),
	Adapter('Barcode 81 (forward)',
		start_sequence=('A11_i5_F', 'TTACGGTAAC'),
		end_sequence=('A11_i7_F', 'ATCACTCACA')),
	Adapter('Barcode 81 (reverse)',
		start_sequence=('A11_i7_R', 'TGTGAGTGAT'),
		end_sequence=('A11_i5_R', 'GTTACCGTAA')),
	Adapter('Barcode 82 (forward)',
		start_sequence=('B11_i5_F', 'TTCAGATGGA'),
		end_sequence=('B11_i7_F', 'CGGAGGTAGA')),
	Adapter('Barcode 82 (reverse)',
		start_sequence=('B11_i7_R', 'TCTACCTCCG'),
		end_sequence=('B11_i5_R', 'TCCATCTGAA')),
	Adapter('Barcode 83 (forward)',
		start_sequence=('C11_i5_F', 'TAGCATCTGT'),
		end_sequence=('C11_i7_F', 'GAGTTGACAA')),
	Adapter('Barcode 83 (reverse)',
		start_sequence=('C11_i7_R', 'TTGTCAACTC'),
		end_sequence=('C11_i5_R', 'ACAGATGCTA')),
	Adapter('Barcode 84 (forward)',
		start_sequence=('D11_i5_F', 'GGACGAGATC'),
		end_sequence=('D11_i7_F', 'GCCGAACTTG')),
	Adapter('Barcode 84 (reverse)',
		start_sequence=('D11_i7_R', 'CAAGTTCGGC'),
		end_sequence=('D11_i5_R', 'GATCTCGTCC')),
	Adapter('Barcode 85 (forward)',
		start_sequence=('E11_i5_F', 'AGGTTCTGTT'),
		end_sequence=('E11_i7_F', 'AGGCCTCACA')),
	Adapter('Barcode 85 (reverse)',
		start_sequence=('E11_i7_R', 'TGTGAGGCCT'),
		end_sequence=('E11_i5_R', 'AACAGAACCT')),
	Adapter('Barcode 86 (forward)',
		start_sequence=('F11_i5_F', 'CATACTCGTG'),
		end_sequence=('F11_i7_F', 'TCTCTGTTAG')),
	Adapter('Barcode 86 (reverse)',
		start_sequence=('F11_i7_R', 'CTAACAGAGA'),
		end_sequence=('F11_i5_R', 'CACGAGTATG')),
	Adapter('Barcode 87 (forward)',
		start_sequence=('G11_i5_F', 'CCGGATACCA'),
		end_sequence=('G11_i7_F', 'TCCGACGATT')),
	Adapter('Barcode 87 (reverse)',
		start_sequence=('G11_i7_R', 'AATCGTCGGA'),
		end_sequence=('G11_i5_R', 'TGGTATCCGG')),
	Adapter('Barcode 88 (forward)',
		start_sequence=('H11_i5_F', 'ATGTCCACCG'),
		end_sequence=('H11_i7_F', 'AGGCTATGTT')),
	Adapter('Barcode 88 (reverse)',
		start_sequence=('H11_i7_R', 'AACATAGCCT'),
		end_sequence=('H11_i5_R', 'CGGTGGACAT')),
	Adapter('Barcode 89 (forward)',
		start_sequence=('A12_i5_F', 'CACCAAGTGG'),
		end_sequence=('A12_i7_F', 'CGTTCTCTTG')),
	Adapter('Barcode 89 (reverse)',
		start_sequence=('A12_i7_R', 'CAAGAGAACG'),
		end_sequence=('A12_i5_R', 'CCACTTGGTG')),
	Adapter('Barcode 90 (forward)',
		start_sequence=('B12_i5_F', 'TTGAGTACAC'),
		end_sequence=('B12_i7_F', 'TTGTCTATGG')),
	Adapter('Barcode 90 (reverse)',
		start_sequence=('B12_i7_R', 'CCATAGACAA'),
		end_sequence=('B12_i5_R', 'GTGTACTCAA')),
	Adapter('Barcode 91 (forward)',
		start_sequence=('C12_i5_F', 'CGGTTCCGTA'),
		end_sequence=('C12_i7_F', 'GATGGATACA')),
	Adapter('Barcode 91 (reverse)',
		start_sequence=('C12_i7_R', 'TGTATCCATC'),
		end_sequence=('C12_i5_R', 'TACGGAACCG')),
	Adapter('Barcode 92 (forward)',
		start_sequence=('D12_i5_F', 'GGAGGTCCTA'),
		end_sequence=('D12_i7_F', 'CACTTAGGCG')),
	Adapter('Barcode 92 (reverse)',
		start_sequence=('D12_i7_R', 'CGCCTAAGTG'),
		end_sequence=('D12_i5_R', 'TAGGACCTCC')),
	Adapter('Barcode 93 (forward)',
		start_sequence=('E12_i5_F', 'CCTGCTTGGA'),
		end_sequence=('E12_i7_F', 'ACACTGGCTA')),
	Adapter('Barcode 93 (reverse)',
		start_sequence=('E12_i7_R', 'TAGCCAGTGT'),
		end_sequence=('E12_i5_R', 'TCCAAGCAGG')),
	Adapter('Barcode 94 (forward)',
		start_sequence=('F12_i5_F', 'TTCACGTCAG'),
		end_sequence=('F12_i7_F', 'ATCGCCACTG')),
	Adapter('Barcode 94 (reverse)',
		start_sequence=('F12_i7_R', 'CAGTGGCGAT'),
		end_sequence=('F12_i5_R', 'CTGACGTGAA')),
	Adapter('Barcode 95 (forward)',
		start_sequence=('G12_i5_F', 'AACATAGCCT'),
		end_sequence=('G12_i7_F', 'CTGACGTGAA')),
	Adapter('Barcode 95 (reverse)',
		start_sequence=('G12_i7_R', 'TTCACGTCAG'),
		end_sequence=('G12_i5_R', 'AGGCTATGTT')),
	Adapter('Barcode 96 (forward)',
		start_sequence=('H12_i5_F', 'TGACATAGTC'),
		end_sequence=('H12_i7_F', 'TCAATCGTCT')),
	Adapter('Barcode 96 (reverse)',
		start_sequence=('H12_i7_R', 'AGACGATTGA'),
		end_sequence=('H12_i5_R', 'GACTATGTCA'))
]

def make_full_native_barcode_adapter(barcode_num):
	barcode = [x for x in ADAPTERS if x.name == 'Barcode ' + str(barcode_num) + ' (reverse)'][0]
	start_barcode_seq = barcode.start_sequence[1]
	end_barcode_seq = barcode.end_sequence[1]

	start_full_seq = 'AATGTACTTCGTTCAGTTACGTATTGCTAAGGTTAA' + start_barcode_seq + 'CAGCACCT'
	end_full_seq = 'AGGTGCTG' + end_barcode_seq + 'TTAACCTTAGCAATACGTAACTGAACGAAGT'

	return Adapter('Native barcoding ' + str(barcode_num) + ' (full sequence)',
		start_sequence=('NB' + '%02d' % barcode_num + '_start', start_full_seq),
		end_sequence=('NB' + '%02d' % barcode_num + '_end', end_full_seq))


def make_old_full_rapid_barcode_adapter(barcode_num):  # applies to SQK-RBK001
	barcode = [x for x in ADAPTERS if x.name == 'Barcode ' + str(barcode_num) + ' (forward)'][0]
	start_barcode_seq = barcode.start_sequence[1]

	start_full_seq = 'AATGTACTTCGTTCAGTTACG' + 'TATTGCT' + start_barcode_seq + \
		'GTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA'

	return Adapter('Rapid barcoding ' + str(barcode_num) + ' (full sequence, old)',
		start_sequence=('RB' + '%02d' % barcode_num + '_full', start_full_seq))


def make_new_full_rapid_barcode_adapter(barcode_num):  # applies to SQK-RBK004
	barcode = [x for x in ADAPTERS if x.name == 'Barcode ' + str(barcode_num) + ' (forward)'][0]
	start_barcode_seq = barcode.start_sequence[1]

	start_full_seq = 'AATGTACTTCGTTCAGTTACG' + 'GCTTGGGTGTTTAACC' + start_barcode_seq + \
		'GTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA'

	return Adapter('Rapid barcoding ' + str(barcode_num) + ' (full sequence, new)',
		start_sequence=('RB' + '%02d' % barcode_num + '_full', start_full_seq))
