#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""Study covered region of given genome.
Takes as input a '.bam' file and a '.gff' file with the mapping against a given
reference and the annotation of that reference. Compute the coverage of all
annotated regions and provides a tsv.
"""

# WARNING - The following has mostly been generated by ChatGPT

"""
coverage_per_locus.py

Compute coverage (depth) statistics for each locus (feature) in a GFF/GTF file
using only PRIMARY alignments from a BAM file.

Output: TSV with one row per feature and columns:
  seqid  start  end  feature_id  feature_type  length  covered_bases
  pct_covered  sum_depth  mean_depth  median_depth  max_depth

Notes:
 - GFF/GTF coordinates are assumed 1-based inclusive (standard). Converted to
   0-based half-open for pysam (start0 = start-1, end0 = end).
 - Primary alignments only: filters out reads with is_secondary or
   is_supplementary True.
 - BAM must be indexed (.bai).
 - For large loci this stores per-base depths to compute median; fo
   extremely large
   regions you can remove median calculation to reduce memory.
"""

import os
import sys

import argparse
import itertools
import numpy as np
import pandas as pd
import pysam
from statistics import median

from typing import List, Tuple, Optional

import utils # import local utility functions

def parse_gff_line(line: str) -> Optional[
    Tuple[str,int,int,str,str,str,str,str]
]:
    """Parse a single GFF/GTF line (skip comments).
    
    Return (seqid, start, end, feat_id, feat_type, gene_biotype, gbkey, gene).
    """

    # Skip comments
    if line.startswith('#'):
        return None
    
    parts = line.rstrip().split()
    if len(parts) < 9:
        return None
    seqid = parts[0]
    feat_type = parts[2]
    try:
        start = int(parts[3])
        end = int(parts[4])
    except ValueError:
        return None

    # extract an identifier from attributes if available (ID here)
    attrs = parts[8]
    feat_id, gene_biotype, gbkey, gene = None, None, None, None
    for key in ('ID', 'gene_id', 'transcript_id', 'Name'):
        # GTF style: key 'value'; GFF3 style: key=value; (latter case here)
        if f'{key}=' in attrs:
            # loose extraction
            for token in attrs.split(';'):
                if token.startswith(key):
                    feat_id = token.split('=', 1)[1]
            break
    if feat_id is None:
        # fallback: use 'type:start-end'
        feat_id = f'{feat_type}:{seqid}:{start}-{end}'
    
    # extract gene biotype
    if 'gene_biotype=' in attrs:
        gene_biotype = attrs.split('gene_biotype=')[1]
        gene_biotype = gene_biotype.split(';')[0]    
    if gene_biotype is None:
        gene_biotype = 'undefined'

    # extract genbank key
    if 'gbkey=' in attrs:
        gbkey = attrs.split('gbkey=')[1]
        gbkey = gbkey.split(';')[0]    
    if gbkey is None:
        gbkey = 'undefined'
    
    # extract gene
    if 'gene=' in attrs:
        gene = attrs.split('gene=')[1]
        gene = gene.split(';')[0]    
    if gene is None:
        gene = 'undefined'
    
    return seqid, start, end, feat_id, feat_type, gene_biotype, gbkey, gene

def coverage_for_region(bam: pysam.AlignmentFile, chrom: str, start1: int,
                        end1: int, min_mapq: int = 0) -> List[int]:
    """
    Compute per-base depth list for region [start1, end1] inclusive (GFF
    coords). Only primary alignments counted: skip read.is_secondary or
    read.is_supplementary. Returns a list of depths (length = end1-start1+1).
    """
    if start1 > end1:
        return []
    start0 = start1 - 1
    end0 = end1  # pysam pileup end is exclusive in fetch/pileup behavior when
    # using start/end arguments

    # Initialize depth array
    length = end1 - start1 + 1
    depths = [0] * length
    # depth_unmap = [0] * length
    # depth_second = [0] * length
    # depth_lowqual = [0] * length
    # depth_delrefskip = [0] * length

    # Use pileup; truncate=True ensures columns outside region are not returned
    # stepper='all' to include all reads that overlap; we will filter by flags
    # below.
    for pileupcolumn in bam.pileup(
        reference=chrom,
        start=start0,
        end=end0,
        truncate=True,
        stepper='all',
        min_base_quality=0
    ):
        pos0 = pileupcolumn.reference_pos  # 0-based
        if pos0 < start0 or pos0 >= end0:
            continue
        idx = pos0 - start0
        count = 0
        # c_unmapped = 0
        # c_secondary = 0
        # c_lowqual = 0
        # c_delrefskip = 0
        for pr in pileupcolumn.pileups:
            r = pr.alignment
            # skip unmapped (shouldn't appear), secondary, supplementary
            if r.is_unmapped:
                # c_unmapped += 1
                continue
            if r.is_secondary or r.is_supplementary:
                # c_secondary += 1
                continue
            if r.mapping_quality < min_mapq:
                # c_lowqual += 1
                continue
            # optionally skip deletions? pileup includes deletions as not
            # contributing to coverage;
            # only count if pr.is_del is False
            if pr.is_del or pr.is_refskip:
                # deletion or refskip -> no base from read at this reference
                # pos
                # c_delrefskip += 1
                continue
            count += 1
        depths[idx] = count
        # depth_unmap[idx] = c_unmapped
        # depth_second[idx] = c_secondary
        # depth_lowqual[idx] = c_lowqual
        # depth_delrefskip[idx] = c_delrefskip

    return depths
    # return depths, depth_unmap, depth_second, depth_lowqual, depth_delrefskip

def summarize_depths(depths: List[int]) -> Tuple[int,int,float,float,int]:
    """Return covered_bases, sum_depth, mean_depth, median_depth, max_depth"""
    if not depths:
        return 0, 0, 0.0, 0.0, 0
    covered = sum(1 for d in depths if d > 0)
    s = sum(depths)
    mean = s / len(depths) if len(depths) else 0.0
    med = median(depths) if len(depths) else 0.0
    m = max(depths) if depths else 0
    return covered, s, mean, med, m

def compute_lib_size(bam_handle, min_mapq, sizes_path=None):
    """
    Sum total read bases across all PRIMARY mapped reads in bam_handle.
    - counts read.query_length for each read
    - skips unmapped, secondary, supplementary
    - respects mapping quality threshold

    Arguments:
    bam_handle     (handle) - file handle corresponding to bam alignment file
    min_mapq    (int|float) - minimum mapping quality to take a read in account
    sizes_path        (str) - path to a txt file containing ROIs in the form of
        tab-separated region name, start and end (one region per line) - this
        defaults to None (i.e. all reads are taken into account)
    """
    total_bases = 0
    target_bases = 0 if sizes_path is not None else None
    if sizes_path:
        targets = {}
        with open(sizes_path, 'r') as target_sizes:
            for target in target_sizes:
                if target.startswith('#'):
                    continue
                t_id, tstart, tend = target.strip().split('\t')
                targets[t_id] = [int(tstart), int(tend)]
    # iterate over entire BAM
    # using fetch(until_eof=True) ensures we walk through all reads in the file
    for read in bam_handle.fetch(until_eof=True):
        if read.is_secondary or read.is_supplementary:
            continue
        if read.mapping_quality < min_mapq:
            continue
        # query_length is the length of the read sequence (int or None)
        qlen = read.query_length
        if qlen is None:
            # fallback if query_length missing: use len(query_sequence)
            seq = read.query_sequence
            qlen = len(seq) if seq is not None else 0
        # increment total bases
        total_bases += qlen
        rstart = read.reference_start
        rend   = read.reference_end
        if sizes_path is None or rstart is None or rend is None:
            continue
        hit = read.reference_name
        if hit in targets:
            overlap = max(
                0, min(rend, targets[hit][1]) - max(rstart, targets[hit][0])
            )
            target_bases += overlap

    return total_bases, target_bases

def compute_target_lib_size(bam_handle, sizes_path, min_mapq):
    """Sum sum_depth over target."""
    target_bases = 0
    with open(sizes_path, 'r') as target_sizes:
        for ln in target_sizes:
            if ln.startswith('#'):
                continue
            seq_id, start, end = ln.strip().split('\t')
            start, end = int(start), int(end)
            depths_tmp = coverage_for_region(
                bam_handle, seq_id, start, end, min_mapq=min_mapq
            )[0]
            # sum_depth for region = sum(depths_tmp)
            target_bases += sum(depths_tmp)
    return target_bases


def main():
    p = argparse.ArgumentParser(description='Per-locus coverage (primary '
                                + 'alignments only) from BAM + GFF/GTF')
    p.add_argument('-b', '--bam', required=True, help='Input BAM (indexed)')
    p.add_argument('-b2', '--bam2', required=False, default=None,
                   help='Optional second BAM (indexed) to compare')
    p.add_argument('-g', '--gff', required=True, help='Input GFF/GTF file '
                   + '(features to process)')
    p.add_argument('-o', '--out', required=False,
                   default='coverage_per_locus.tsv', help='Output TSV')
    p.add_argument('--feature_type', default=None, help='Only compute for '
                   + 'features of this type (e.g. gene, exon). Default: all')
    p.add_argument('--gene_biotype', default=None, help='Only compute for '
                   + 'biotypes of this type (e.g. protein_coding). Default: '
                   + 'all')
    p.add_argument('--gbkey', default=None, help='Only compute for genbank '
                   + 'keys of this type (e.g. rRNA). Default: all')
    p.add_argument('--min_mapq', type=int, default=0, help='Minimum mapping '
                   + 'quality to count read. Default: 0')
    p.add_argument('--pseudocount', type=float, default=1e-3,
                   help='Pseudocount added to normalized mean (CPM per base) '
                   + 'before log2; default 1e-3')
    p.add_argument('--target', type=str, help='List of target chromosomes and '
                   + 'sizes.')
    p.add_argument('-v', '--verbose', type=int, default=0,
                   help='Degree of verbosity. Default: 0 = muted')
    args = p.parse_args()

    v = args.verbose

    utils.send_text('Checking input bam file and index', v, 1, 0)
    try:
        bam = pysam.AlignmentFile(args.bam, 'rb')
    except Exception as e:
        sys.exit(f'Error opening BAM: {e}')

    # Ensure BAM is indexed (pysam will error if not when using fetch/pileup)
    try:
        _ = bam.get_index_statistics()
    except Exception:
        sys.exit(
            'BAM does not appear indexed or cannot access index (.bai). Index '
            + 'the BAM first (samtools index).'
        )
    
    bam2 = None
    if args.bam2:
        utils.send_text('Checking second input bam file and index', v, 1, 0)
        try:
            bam2 = pysam.AlignmentFile(args.bam2, 'rb')
        except Exception as e:
            sys.exit(f'Error opening second BAM: {e}')
        try:
            _ = bam2.get_index_statistics()
        except Exception:
            sys.exit('Second BAM does not appear indexed or cannot access '
                     + 'index (.bai). Index it first (samtools index).')
    
    utils.send_text('Computing library size (all mapped reads bases, for reads'
                    + ' over given mapping quality threshold - set to '
                    + f'{args.min_mapq})', v, 1, 0)
    lib_size1, t_lib_size1 = compute_lib_size(bam, args.min_mapq, args.target)
    if lib_size1 == 0:
        lib_size1 = 1
        utils.send_text(f'WARNING: No bases found.', v, 1, 1)
    else:
        utils.send_text(f'Total nb of bases: {lib_size1}', v, 1, 1)
    if args.target:
        utils.send_text(f'Nb of bases mapping target: {t_lib_size1}', v, 1, 1)
        if t_lib_size1 == 0: t_lib_size1 = 1
    
    if bam2 is not None:
        utils.send_text('Computing library size for second sample', v, 1, 0)
        lib_size2, t_lib_size2 = compute_lib_size(
            bam2, args.min_mapq, args.target
        )
        if lib_size2 == 0:
            lib_size2 = 1
            utils.send_text(f'WARNING: No bases found in 2nd bam.', v, 1, 1)
        else:
            utils.send_text(f'Total nb of bases for 2nd bam: {lib_size2}',
                            v, 1, 1)
        if args.target:
            utils.send_text(
                f'Nb of bases mapping target in 2nd bam: {t_lib_size2}',
                v, 1, 1
            )
            if t_lib_size2 == 0: t_lib_size2 = 1

    out_f = open(args.out, 'w')
    header = [
        'seqid', 'start', 'end', 'feature_id', 'feature_type', 'gene_biotype',
        'gbkey', 'gene', 'length',
        # BAM1 fields
        'mean_depth_1', 'norm_depth_1'
        # 'mean_depth_1', 'mean_unmap', 'mean_second', 'mean_lowqual',
        # 'mean_delrefskip', 'norm_depth_1'
    ]
    if args.target:
        header.append('target_norm_depth_1')
    header += [
        'covered_bases_1', 'pct_covered_1', 'sum_depth_1', 'median_depth_1',
        'max_depth_1'
    ]
    if bam2 is not None:
        header += [
            # BAM2 fields
            'mean_depth_2', 'norm_depth_2'
        ]
        if args.target:
            header.append('target_norm_depth_2')
        header += [
            'covered_bases_2', 'pct_covered_2', 'sum_depth_2',
            'median_depth_2', 'max_depth_2',
            # differences (BAM2 - BAM1)
            'pct_covered_diff', 'mean_depth_diff', 'robust_log2fc', 'log2fc',
            'target_robust_log2fc', 'target_log2fc'
        ]

    out_f.write('\t'.join(header) + '\n')

    utils.send_text(
        'Parse annotation gff and compute statistics for each locus', v, 1, 0
    )
    valid_loci = 0
    skipped_loci = 0
    with open(args.gff) as gf:
        for line in gf:
            parsed = parse_gff_line(line)
            if parsed is None:
                continue
            seqid,start,end,feat_id,feat_type,gene_biotype,gbkey,gene = parsed
            if args.feature_type and feat_type != args.feature_type:
                skipped_loci += 1
                continue
            if args.gene_biotype and gene_biotype != args.gene_biotype:
                skipped_loci += 1
                continue
            if args.gbkey and gbkey != args.gbkey:
                skipped_loci += 1
                continue
            utils.send_text(f'Computing statistics for {feat_id}...', v, 3, 2)
            
            # Compute per-base depths
            # depths1, d_unmap, d_second, d_lowqual, d_delrefskip = coverage_for_region(
            depths1 = coverage_for_region(
                bam,
                seqid,
                start,
                end,
                min_mapq=args.min_mapq
            )
            covered1, s1, mean1, med1, m1 = summarize_depths(depths1)
            # _, _, mean_unmap,_ , _ = summarize_depths(d_unmap)
            # _, _, mean_second,_ , _ = summarize_depths(d_second)
            # _, _, mean_lowqual,_ , _ = summarize_depths(d_lowqual)
            # _, _, mean_delrefskip,_ , _ = summarize_depths(d_delrefskip)
            length = end - start + 1
            pct_cov1 = (covered1 / length * 100.0) if length > 0 else 0.0
            norm_mean1 = (mean1 / lib_size1) * 1e6
            if args.target:
                target_norm_mean1 = (mean1 / t_lib_size1) * 1e6

            if bam2 is not None:
                depths2 = coverage_for_region(
                    bam2,
                    seqid,
                    start,
                    end,
                    min_mapq=args.min_mapq
                )
                covered2, s2, mean2, med2, m2 = summarize_depths(depths2)
                pct_cov2 = (covered2 / length * 100.0) if length > 0 else 0.0
                norm_mean2 = (mean2 / lib_size2) * 1e6
                if args.target:
                    target_norm_mean2 = (mean2 / t_lib_size2) * 1e6

                pct_cov_diff = pct_cov2 - pct_cov1
                mean_depth_diff = mean2 - mean1
                pc = args.pseudocount
                rlog2fc = float(np.log2((norm_mean2 + pc) / (norm_mean1 + pc)))
                log2fc = 'undefined'
                if norm_mean2 > 0 and norm_mean1 > 0:
                    log2fc = float(np.log2((norm_mean2) / (norm_mean1)))
                if args.target:
                    target_rlog2fc = float(
                        np.log2(
                            (target_norm_mean2 + pc) / (target_norm_mean1 + pc)
                        )
                    )
                    target_log2fc = 'undefined'
                    if target_norm_mean2 > 0 and target_norm_mean1 > 0:
                        target_log2fc = float(
                            np.log2((target_norm_mean2) / (target_norm_mean1))
                        )
            
            # Build target output fields
            fields = [
                seqid,
                str(start),
                str(end),
                feat_id,
                feat_type,
                gene_biotype,
                gbkey,
                gene,
                str(length),
                # BAM1
                f'{mean1:.6g}',
                # f'{mean_unmap:.6g}',
                # f'{mean_second:.6g}',
                # f'{mean_lowqual:.6g}',
                # f'{mean_delrefskip:.6g}',
                f'{norm_mean1:.6f}'
            ]
            if args.target:
                fields.append(f'{target_norm_mean1:.6f}')
            fields += [
                str(covered1),
                f'{pct_cov1:.3f}',
                str(s1),
                f'{med1:.3f}',
                str(m1)
            ]
            # BAM2
            if bam2 is not None:
                fields += [
                    f'{mean2:.6g}',
                    f'{norm_mean2:.6f}'
                ]
                if args.target:
                    fields.append(f'{target_norm_mean2:.6f}')
                fields += [
                    str(covered2),
                    f'{pct_cov2:.3f}',
                    str(s2),
                    f'{med2:.3f}',
                    str(m2),
                    # diffs
                    f'{pct_cov_diff:.3f}',
                    f'{mean_depth_diff:.6f}',
                    f'{rlog2fc:.6f}',
                ]
                if log2fc == 'undefined':
                    fields.append(log2fc)
                else:
                    fields.append(f'{log2fc:.6f}')
                if args.target:
                    fields += [
                        f'{target_rlog2fc:.6f}',
                    ]
                    if target_log2fc == 'undefined':
                        fields.append(target_log2fc)
                    else:
                        fields.append(f'{target_log2fc:.6f}')
            
            valid_loci += 1
            if v > 1 and valid_loci % 500 == 0:
                utils.send_text(
                    f'Found {valid_loci} valid loci... ({skipped_loci} '
                    + 'skipped)', v, 3, 2
                )
            
            out_f.write('\t'.join(fields) + '\n')

        
        utils.send_text(
            f'Found {valid_loci} valid loci... ({skipped_loci} '
            + 'skipped)', v, 2, 1
        )

    out_f.close()
    bam.close()
    if bam2 is not None:
        bam2.close()

    return 0

if __name__ == '__main__':
    main()